version: '3'

networks:
  epts:

volumes:
  mysql-data:

services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "eSaude1234"
      MYSQL_DATABASE: "openmrs"
      MYSQL_USER: "openmrs"
      MYSQL_PASSWORD: "openmrs"
    ports:
      - "3306:3306"
    command: --max_allowed_packet=32505856
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - epts

  tomcat7:
    container_name: tomcat7
    image: tomcat:7-jre7-alpine
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true -Xmx40G -Xms40G -XX:MaxPermSize=40G -XX:+UseConcMarkSweepGC"
    networks:
      - epts
    depends_on:
      - mysql

